version: "3.8"
services:

  elasticsearch:
    image: elasticsearch:7.9.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    image: kibana:7.9.0
    ports:
      - "5601:5601"
    networks:
      - elastic

networks:
  elastic:
